### ISSUE TITLE
Phasmophobia auto splitter does not start, split

### ISSUE THREAD

**Issue by boomboompower** [just-ero/AutoSplitTools#1]
## *Context*
Game name (as it appears on this repo): Phasmophobia

- [x] The game has recently received an update

---
## *Which Features are Broken?*
(*do not check any features which didn't exist to begin with*)

- [x] Start
- [x] Split
- [ ] Reset  
- [ ] Load removal / Game time synchronization

---
## *Describe your Issue*
- [ ] The features checked above outright do not work  
If there is any especially weird behavior with the timer, please describe what is happening: "Sometimes doesn't split at all, and sometimes splits 0.03 seconds after start, however most of the time it doesn't start/split at all"

---
## *Causes and Fixes*
(*for experienced users only*)

Likely broken addresses due to the update, however I do not have any recommendations or fixes for the issues.

---
## *Common Issues*
*Only load removal / game time sync is broken, everything else works*: Please make sure you are comparing against Game Time within LiveSplit.  
*The auto splitter cannot be activated from the splits editor*: Try launching LiveSplit as administrator. If the issue persists after that, it is a bug on LiveSplit's side.

**Comment by just-ero** [comment]
Fixed in 585825cc2888e0a27b6af9af4a84c38b37ad6ae9.  
**This fix also introduces load removal.** The timer (when compared to Game Time) will pause when a map is loading and as long as not all users are connected.
