### ISSUE TITLE
[Gunfire Reborn] autosplitter does not [start, split, reset, remove loads, sync to game time]

### ISSUE THREAD

**Issue by Pimmalage** [just-ero/AutoSplitTools#3]
---
## *Describe your Issue*
- Game recently got a larger update, seems to have broken the Start function, possibly Cannot test beyond that since the auto-splitter automatically starts the timer.
- A Smaller update before this larger one also broke the Final split function (Didn't report instantly since it was fine to work around, and i assume a larger update would break other functions)
---
## *Causes and Fixes*
The Final level got an alternate boss and a slightly modified arena - Possible that the final alternate zone has a different level/leveltype

**Comment by just-ero** [comment]
Fixed in 1812faf69f6634aeb79f9dd74913fe1516bb1f73.
