### ISSUE TITLE
[Gunfire Reborn] autosplitter does not [start, split, reset, sync to game time]

### ISSUE THREAD

**Issue by Pimmalage** [just-ero/AutoSplitTools#4]
Please refer to the [common issues](https://github.com/just-ero/AutoSplitTools#common-auto-splitter-issues) before creating an issue.

---
## *Describe your Issue*
- Sync, Start/split and reset are all not functioning.
- Tested in-game time with a manual livesplit start and didn't sync, Reset and Splits also seem to not trigger on level load and navigating back to menu.

---
## *Causes and Fixes*
- Game update, Even though a much smaller game update it still affected the sigs. (Fingers crossed not a common occurrence from now on)

**Comment by just-ero** [comment]
Fixed in a183ca5f14742974e49fffa671d155306e860916.
