### ISSUE TITLE
Auto splitter and load remover for A plague tales innocence

### ISSUE THREAD

**Issue by Draghann** [just-ero/AutoSplitTools#6]
[x] I have read and understood these terms.

---
## *Auto splitter and load remover for A plague tales innocence*
*Auto splitter and load remover *:
* A Plague tales innocence: 

*Please describe where the need for this feature arises from*:  
Ex.: this game is a lot of loading screen, after each chapter (17 chapters). so if you don't have a good pc like me, it's complicated to run correctly.

*Please elaborate on the exact feature(s) and their expected behavior*:  
Good: I want the timer  split  after skipping the final cute scene of each chapter.  Load removal on each loading screen of each chapter

---
## *Auto Splitter Commission*
*Auto splitter and load remover for A plague tales innocence*:
*  A Plague tales innocence: 
* https://store.steampowered.com/app/752590/A_Plague_Tale_Innocence/ or on xbox game pass pc *): 

*Features*:  
  
[x] Split:  split after skipping the final cute scene of each chapter.  
[x] Load removal on each loading screen of each chapter

**Comment by just-ero** [comment]
I will not be working on this game. The engine is proprietary and a nightmare to work with.
